### ISSUE TITLE
Clang Reports Use of Uninitialized Variable

### ISSUE THREAD

**Issue by breannansmith** [sweeneychris/RpolyPlusPlus#4]
Clang complains that the uninitialized variable 'polynomial_at_root' at line 603 of find_polynomial_roots_jenkins_traub.cc is assigned to 'prev_polynomial_at_root' at line 618, which is subsequently used uninitialized.

**Comment by sweeneychris** [comment]
I just pushed what should be a fix for this. Please let me know if this allows the library to compile properly for clang

**Comment by breannansmith** [comment]
Rad, that seems to fix the issue. Thanks!
